### ISSUE TITLE
use of randomElementModQ when encrypting

### ISSUE THREAD

**Issue by danwallach** [danwallach/electionguard-kotlin-multiplatform#113]
Right now, we have two calls to `group.randomElementModQ()` in `Encryptor.kt`. These cause the encryption process to be non-deterministic. Ideally, encryption should have the option to be deterministic, so if you know the seed nonce(s), then you can derive all of the other nonces, all the way down.

We could have a flag when the `Encryptor` object is created that says "go ahead and be non-deterministic", which might be useful in some circumstances.

**Comment by JohnLCaron** [comment]
In Encryptor.kt, we now have two methofs:

```
fun encrypt(
      ballots: Iterable<PlaintextBallot>, 
      codeSeed: ElementModQ
   ): List<CiphertextBallot> 
```

and

```
fun encryptWithFixedNonces(
        ballots: Iterable<PlaintextBallot>,
        codeSeed: ElementModQ,
        masterNonce: ElementModQ
    ): List<CiphertextBallot>
```

which I think? handles this issue.

We do need to add deterministic option for the ContestData encryption, see issue #164

**Comment by JohnLCaron** [comment]
All done
