### ISSUE TITLE
Generating nonces for encryption

### ISSUE THREAD

**Issue by danwallach** [danwallach/electionguard-kotlin-multiplatform#115]
https://github.com/danwallach/electionguard-kotlin-multiplatform/blob/fbcea2921e87b2eb1bd0e6161937078c4381ca76/src/commonMain/kotlin/electionguard/encrypt/Encryptor.kt#L198-L199

Several places, the encryption code computes nonces like so:
```kotlin
val nonceSequence =
    Nonces(selectionDescription.cryptoHash.toElementModQ(group), contestNonce)
val disjunctiveChaumPedersenNonce: ElementModQ = nonceSequence.get(0)
val selectionNonce: ElementModQ = nonceSequence.get(selectionDescription.sequenceOrder)
```

This probably wants to look more like:
```kotlin
val (disjunctiveChaumPedersenNonce, selectionNonce) = Nonces(...) 
```
That gets the 0th and 1st nonce from the sequence, rather than getting the nth element. This *should* be okay, since each selection will have a different `selectionDescription`, so there will be no repetition of nonces across different candidates.

That specific property, by the way, should be a property-based test, if it isn't already. Pretty much all you have to do is rummage through all the `ElGamalCiphertext` objects inside an encrypted ballot and assert that the `pad` part ($g^R$) never repeats.

**Comment by JohnLCaron** [comment]
Im working on Encryptor.kt, so ill take this one

**Comment by JohnLCaron** [comment]
Looks like it occcurs in two places, encryptSelection() and encryptContest().

Using the contest hash to create the Nonces:

`        val nonceSequence = Nonces(contestDescriptionHashQ, ballotNonce)
`

makes sure that each contest's nonceSequence is unique.

In the current code, you will get same nonce for 

````
        val contestNonce = nonceSequence[mcontest.sequenceOrder]
        val chaumPedersenNonce = nonceSequence[0]
````

for sequenceOrder = 0.

Similarly for the selections, mutatis mutandi.
