### ISSUE TITLE
contest encryption won't work with overvoted inputs

### ISSUE THREAD

**Issue by danwallach** [danwallach/electionguard-kotlin-multiplatform#116]
If the `PlaintextBallot.Contest` is "overvoted" (i.e., has more selections than are allowed for by the ballot style), then we have a problem. We cannot correctly encrypt it in such a way that all the proofs will check out, because, among other things, the sum of the encrypted selections plus the placeholders won't equal the expected total.

We solved this in arlo-cvr-encryption by having an `_interpret_contest` function that would check for overvoting and return a `PlaintextBallotSelection` of all zeros.
https://github.com/votingworks/arlo-cvr-encryption/blob/b20a27f0ecb24c39268fdc9123f5367e3f967857/src/arlo_cvre/tally.py#L114

The proper ElectionGuard answer is inadequately specified. According to the EG 1.02 spec (p. 16):

> When the number of selections made by the voter exceeds the selection limit for a specific contest, the votes in the contest become invalid as an overvote. To not affect the election tallies, all selectable options in the contest are set to zero (unselected) and all placeholder options are set to one (selected). To record that an overvote has occurred and what specific selections were made by the voter in this contest, this information is encoded into an extended data field possibly together with other data such as write-in text fields. This data is then encrypted to the election public key using the hashed ElGamal encryption described in Section 3.

The spec is silent on exactly what's supposed to go in the extended data field, but it could potentially be a JSON object corresponding to all the PlaintextBallotSelections, then encrypted with the hashed ElGamal cipher. It could be other things as well. Do we do this once per selection? Do we do it once per contest? Presumably, this should *always* be present, even when ballots aren't overvoted, so that its presence or absence doesn't communicate any information. 

Write-ins could also go there, but that appears to be a future topic, or at least a separate issue.

**Comment by JohnLCaron** [comment]
I think we have this handled now in 1.52, though (hopefully) we may refine things for 2.0.
