### ISSUE TITLE
EG Spec 1.03: Things not done here

### ISSUE THREAD

**Issue by JohnLCaron** [danwallach/electionguard-kotlin-multiplatform#124]
1. Handling alternative constants 
2. Encryption of contest data (over votes / write ins)
3. Confirmation codes
4. Validation of confirmation codes

double check on validations
11.C, 11.D, 11.E

**Comment by JohnLCaron** [comment]
We are currently generating a confirmation (aka tracking) code, and storing it in _EncryptedBallot.code_. We are not trying to follow the 1.0 spec by including the "previous" ballot, aka ballot chaining. Much to be discussed for version 2, as Dan explains above.

Generating the confirmation code when encrypting and giving it immediately to the user is an important component of detecting any post-encryption modification of the election record, because the confirmation code is (or contains) a hash of the  encrypted ballot. The fact that there is an encrypted ballot with that code proves that the ballot is included in the tally.

**Comment by danwallach** [comment]
I'm increasingly thinking that this design would make for a good student project. It's separate from everything else, and would be worth having a semester-long exercise where they try to understand the requirements, draft a proposal, and then implement it.

**Comment by JohnLCaron** [comment]
superceded by spec 1.52
