### ISSUE TITLE
Investigate using gradle cpp_library plugin

### ISSUE THREAD

**Issue by JohnLCaron** [danwallach/electionguard-kotlin-multiplatform#144]
If we get some gradle expertise, we could look at using this to build libhacl:

https://docs.gradle.org/current/userguide/building_cpp_projects.html#building_cpp_projects

```
plugins {
    cpp-library
}
```

**Comment by danwallach** [comment]
Agreed. I investigated this in the beginning and you'll see it in some of the early commits. I ultimately gave up and went with cmake since it seemed to be relatively smart about portably compiling lots of C code.

**Comment by danwallach** [comment]
Actually it was in a different repo, not this one, where I was experimenting with making multiplatform work at all. That one isn't public, but for whoever is reading this, I can share my work. I had a lot of trouble with the cpp plugin.

**Comment by JohnLCaron** [comment]
refactored hacl library into its own module (PR#194). kept the Cmake build. closing for now.
