### ISSUE TITLE
new extended base hash?

### ISSUE THREAD

**Issue by danwallach** [danwallach/electionguard-kotlin-multiplatform#149]
computation of Q-bar, bottom of page 14

**Comment by JohnLCaron** [comment]
This is a change from version 1 and our pre-1.51 code:

"the base hash Q is hashed with the election public key K and all the guardians’ key commitments Ki,j to form an extended base hash"

Qbar = H(Q, K, K1,0, K1,1, . . . , K1,k−1, K2,0, . . . , Kn,k−2, Kn,k−1)    (20)

**Comment by JohnLCaron** [comment]
fixed by #157
