### ISSUE TITLE
replace existing NIZK proofs with range proofs?

### ISSUE THREAD

**Issue by danwallach** [danwallach/electionguard-kotlin-multiplatform#153]
- 0-or-1 on selection (disjunctive) vs. range proof?
  - is it more efficient to use range proofs everywhere or better to keep the 0-or-1 disjunctive proofs when what we want is a range of [0, 1]?
  - software engineering: it's preferable to use range proofs everywhere and eliminate disjunctive proofs
- no placeholders means we definitely need range proofs for contest limits
- presumably, for constant proofs, the overhead of range proofs is not desirable

Spec p. 20 ("verification 4") walks through range proof verification

**Comment by JohnLCaron** [comment]
Im going to hold off touching anything from ChaumPedersen.kt until you have stabilized code.

I earlier did some stuff with

 * @param hashHeader Optional additional values to include in the start of the challenge computation hash.
 * @param hashFooter Optional additional values to include in the end of the challenge computation hash.

to try to make general interfaces. esp influenced by the attached doc. not sure if new changes affect that.

youre welcome to redo or refactor any of that, as you see fit. Willing to review if you want.

**Comment by JohnLCaron** [comment]
[electionguard_proofs.pdf](https://github.com/danwallach/electionguard-kotlin-multiplatform/files/9636266/electionguard_proofs.pdf)

**Comment by danwallach** [comment]
I'm looking forward to tackling this part of the implementation. Hopefully over the weekend.

**Comment by danwallach** [comment]
Done!
