### ISSUE TITLE
Review HashedElGamalCiphertext for correctness and performance

### ISSUE THREAD

**Issue by JohnLCaron** [danwallach/electionguard-kotlin-multiplatform#161]

**Comment by JohnLCaron** [comment]
Test code was generating a new elGamalKeyPairFromRandom() for each test.
Since its a new public key, it had to create the acceleration tables each time.
thus each HashedElGamalCiphertext was taking 160 msecs instead of ~5.

**Comment by danwallach** [comment]
Yeah, that'll do it.

**Comment by JohnLCaron** [comment]
It occurs to me there may be lots of tests that are populating the acceleration tables over and over again.
Maybe we can create a standard election_key that everyone uses when possible.

**Comment by danwallach** [comment]
Or just use the tinyGroup. That's really fast, no matter what.
