### ISSUE TITLE
Add capability to decrypt contest data with nonce

### ISSUE THREAD

**Issue by JohnLCaron** [danwallach/electionguard-kotlin-multiplatform#164]
Also, currently we are not using the master nonce to set the contest data nonce; its always random. That will also need to be added.

**Comment by JohnLCaron** [comment]
Also see #155

**Comment by danwallach** [comment]
I just added `HashedElGamalCiphertext.decryptWithNonce`, which is what you need to decrypt the contest data with the nonce.

**Comment by JohnLCaron** [comment]
Done, PR#183
