### ISSUE TITLE
ChaumPedersen challenge not following the 1.52 spec

### ISSUE THREAD

**Issue by JohnLCaron** [danwallach/electionguard-kotlin-multiplatform#211]
spec has:

(4.5) c = H(Q, K, α, β, a0 , b0 , a1 , b1 ).
(5.3) c = H(Q, K, ᾱ, β̄, a0 , b0 , a1 , b1 , . . . , aL , bL ).

we have:

    val c = hashElements(qbar, alpha, beta, *(hashMe.toTypedArray())).toElementModQ(context)

should be:

    val c = hashElements(qbar, publicKey, alpha, beta, *(hashMe.toTypedArray())).toElementModQ(context)

Note we use RangeChaumPedersenProofKnownNonce for both cases 4.5, 5.3.

**Comment by danwallach** [comment]
Makes sense to add the public key. Possibly improves security, although it's a stretch. Definitely we want to be compatible with the spec. Need to double-check the `hashMe` part for matching the required `a0, b0, a1, b1, ...` part.

**Comment by JohnLCaron** [comment]
Fixed PR#212
