### ISSUE TITLE
add support for EG 2.0 encryption

### ISSUE THREAD

**Issue by danwallach** [danwallach/electionguard-kotlin-multiplatform#38]
EG 2.0 encryption changes from using the generator as the base for encoding the 0-or-1 counter to using the public key. This ultimately removes the need for one of the modular exponentiation operations in the disjunctive Chaum-Pedersen proof.

Changes that will be required:
- Add support for discrete log for multiple base values
- Changing the encryption / decryption code
- Change the Chaum-Pedersen proof computation
- Change all the unit tests around

**Comment by JohnLCaron** [comment]
Tests are passing. 
I think this can be closed, do you agree [danwallach](https://github.com/danwallach)?
